/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(bb60c_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8495d47c2b34cb3a9416786485b7cdce)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <shbb60/bb60c_source.h>
// pydoc.h is automatically generated in the build directory
#include <bb60c_source_pydoc.h>

void bind_bb60c_source(py::module& m)
{

    using bb60c_source    = gr::shbb60::bb60c_source;


    py::class_<bb60c_source,
        gr::block,
        std::shared_ptr<bb60c_source>>(m, "bb60c_source", D(bb60c_source))

        .def(py::init(&bb60c_source::make),
           py::arg("center_freq"),
           py::arg("ref_level"),
           py::arg("decimation"),
           py::arg("filter_bw"),
           D(bb60c_source,make)
        )
        



        ;




}








