/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-shbb60
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SHBB60_API_H
#define INCLUDED_SHBB60_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_shbb60_EXPORTS
#define SHBB60_API __GR_ATTR_EXPORT
#else
#define SHBB60_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SHBB60_API_H */
